development:
  adapter: postgresql
  encoding: unicode
  database: todonts_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: todonts_test
  pool: 5
  host: localhost
